### ISSUE TITLE
[BUG] 在强制为竖屏模式时启动PojavZH会崩溃

### ISSUE THREAD

**Issue by Silvigarabis** [HopiHopy/PojavZH#17]
# 问题

我在安装了 <https://github.com/HopiHopy/PojavZH/releases/tag/9939872> 这一版本后，尝试启动应用时出现崩溃问题。后来，我发现如果我不锁定竖屏状态（通过第三方软件）再启动，就不会崩溃。

# 复现

1. 从上方链接的版本中下载apk进行安装。
2. 使用一些方法让设备固定为竖屏模式且不允许应用旋转屏幕。
3. 启动程序，提示需要存储权限，允许。
4. 崩溃。
5. 尝试重启，再次崩溃。
6. 不固定为竖屏模式。
7. 再次尝试启动，成功。

# 日志还有其他

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch.zh/net.kdt.pojavlaunch.LauncherActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0020
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7555)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0020
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:291)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2324)
	at android.content.res.Resources.getLayout(Resources.java:1307)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:200)
	at android.app.Activity.performCreate(Activity.java:7343)
	at android.app.Activity.performCreate(Activity.java:7333)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
	... 9 more
```

![Screenshot_20240330225728](https://github.com/HopiHopy/PojavZH/assets/73000464/06368f3a-62cf-4d18-86bc-132700eb11d1)

# 预期行为

横屏启动不是预期行为，但是是否需要为此添加一个提示呢？而不是崩溃。我不确定正常情况下是否会遇到这样的问题，毕竟在正常情况下，手机上并不存在固定竖屏模式的设置。
如果你们认为不需要考虑这种情况，请直接关闭此issue。

# 设备信息

```markdown
- Device model: Huawei DUB-AL00
- CPU architecture: arm64
- Android version: 8.1.0
- PojavLauncher version: edelweiss-20240330-ac772cb-v3_openjdk
```

# 其他

- 我将Releases中的各个版本都试了一下，发现最后一个可以在强制竖屏模式下正常启动到主界面的版本是<https://github.com/HopiHopy/PojavZH/releases/20240318-9939631>。通过检查发布说明，我发现它的更新一个版本 <https://github.com/HopiHopy/PojavZH/releases/20240323>，中包含“强制横屏布局，重构横屏布局”的描述，我猜测这是导致错误的原因。
- 我又从 <https://github.com/HopiHopy/PojavZH/actions/runs/8490865494> 中下载了构建产出的三个版本安装进行了测试，发现均出现类似的问题。
- 我还尝试在不锁定竖屏的情况下正常启动到主界面，而后固定为竖屏模式，这样并不会出现崩溃，而是以竖屏模式展示应用的主界面。
- 这是我首次尝试使用这一应用。

**Comment by HopiHopy** [comment]
我更新了PojavZH的布局为横屏，并删除了竖屏布局。由于不再支持竖屏模式，如果尝试使用竖屏模式会遇到应用崩溃的问题，我不建议这样做，除非有特殊需求。至于后续是否为竖屏模式添加一条警告弹窗，我也可以尝试。
