### ISSUE TITLE
打开游戏就闪退

### ISSUE THREAD

**Issue by discobirch** [HopiHopy/PojavZH#37]
### 问题描述

一打开游戏就闪退

### 日志/截图或视频

![1716144148536](https://github.com/HopiHopy/PojavZH/assets/120728361/03cfffb5-f01a-4120-866d-494abd1f36ff)

### 复现步骤

```markdown
java.lang.RuntimeException: Unable to start service net.kdt.pojavlaunch.services.GameService@6c7c5f4 with Intent { cmp=net.kdt.pojavlaunch.zh/net.kdt.pojavlaunch.services.GameService }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{a86531d 26498:net.kdt.pojavlaunch.zh:game/u0a301} targetSDK=34
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5736)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2908)
	at android.os.Handler.dispatchMessage(Handler.java:117)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:302)
	at android.app.ActivityThread.main(ActivityThread.java:9637)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1062)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{a86531d 26498:net.kdt.pojavlaunch.zh:game/u0a301} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
	at android.os.Parcel.readParcelable(Parcel.java:4872)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3072)
	at android.os.Parcel.createException(Parcel.java:3061)
	at android.os.Parcel.readException(Parcel.java:3044)
	at android.os.Parcel.readException(Parcel.java:2986)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6833)
	at android.app.Service.startForeground(Service.java:781)
	at net.kdt.pojavlaunch.services.GameService.onStartCommand(GameService.java:48)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5716)
	... 9 more
```

### 预期行为

打开游戏就闪退

### 其他信息

```markdown
- 设备型号：MAA-AN00
- CPU 架构：8gen2
- Android 版本：14
- PojavZH 版本：1.0.9.1
```

**Comment by HopiHopy** [comment]
@discobirch 感谢你的反馈，我们已经修复了这个问题，下一个正式版将不再会有此问题出现！下一个正式版将在不久后更新！
