### ISSUE TITLE
无法启动游戏[BUG] 简短的描述

### ISSUE THREAD

**Issue by thousand111** [HopiHopy/PojavZH#38]
### 问题描述

下载好游戏后无法正常启动

### 日志/截图或视频

java.lang.RuntimeException: Unable to start service net.kdt.pojavlaunch.services.GameService@64cff5a with Intent { cmp=net.kdt.pojavlaunch.zh/net.kdt.pojavlaunch.services.GameService }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{b5cd36 14427:net.kdt.pojavlaunch.zh:game/u0a348} targetSDK=34
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5071)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{b5cd36 14427:net.kdt.pojavlaunch.zh:game/u0a348} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7270)
	at android.app.Service.startForeground(Service.java:775)
	at net.kdt.pojavlaunch.services.GameService.onStartCommand(GameService.java:48)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5053)
	... 9 more

Uploading Screenrecorder-2024-05-20-12-11-33-399.mp4…

### 复现步骤

```markdown
打开启动器（刚安装好的）
选择安装新实例（渲染引擎及java均为默认）
安装1.20.6 fabric实例
安装完成
启动游戏
启动失败（更换为java21同样失败）
```

### 预期行为

我不到啊

### 其他信息

```markdown
- 设备型号：redmi k60
- CPU架构：arm v9
- Android 版本：14
- PojavZH 版本：1.09.1
```

**Comment by HopiHopy** [comment]
@thousand111 感谢你的反馈，我们已经修复了这个问题，下一个正式版将不再会有此问题出现！下一个正式版将在不久后更新！
