### ISSUE TITLE
启动游戏时出现启动器崩溃现象

### ISSUE THREAD

**Issue by PumpkinOrca** [HopiHopy/PojavZH#39]
### 问题描述

正在排除是否为下载资源失败导致文件下载不全崩溃

### 日志/截图或视频

java.lang.RuntimeException: Unable to start service net.kdt.pojavlaunch.services.GameService@f16f44 with Intent { cmp=net.kdt.pojavlaunch.zh/net.kdt.pojavlaunch.services.GameService }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{9889c41 7685:net.kdt.pojavlaunch.zh:game/u0a218} targetSDK=34
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5125)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{9889c41 7685:net.kdt.pojavlaunch.zh:game/u0a218} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7270)
	at android.app.Service.startForeground(Service.java:775)
	at net.kdt.pojavlaunch.services.GameService.onStartCommand(GameService.java:48)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5107)
	... 9 more
![Screenshot_2024-05-20-22-17-36-861_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/151600265/99aa2c9d-8b59-481e-8eb3-75f4212c439c)

### 复现步骤

```markdown
1.打开启动器
2.下载游戏资源
3.出现网络错误现象
4.启动游戏
5.启动器崩溃
```

### 预期行为

*

### 其他信息

```markdown
- 设备型号：23046PNC9C
- CPU 架构：Mediatek Dimensity 8200
- Android 版本：14
- PojavZH 版本：1.0.9.1
```

**Comment by HopiHopy** [comment]
@PumpkinOrca 感谢你的反馈，我们已经修复了这个问题[（修复日志）](https://github.com/HopiHopy/PojavZH/commit/c8981b854bb4a07a6f19937ae724f630fb98a130) ，下一个正式版将不再会有此问题出现！下一个正式版将在不久后更新！
