### ISSUE TITLE
virgl运行游戏导致软件崩溃

### ISSUE THREAD

**Issue by Rogertaf** [HopiHopy/PojavZH#46]
### 问题描述

virgl运行游戏导致软件崩溃，我试了好多次，都一样

### 日志/截图或视频

![Screenshot_20240608_045013_net kdt pojavlaunch zh](https://github.com/HopiHopy/PojavZH/assets/171431559/7f1d6ec6-7ada-4ca5-b6a4-0a71fff7e4a9)

### 复现步骤

```markdown
1.打开启动器
2.运行游戏
3.软件崩溃
```

### 预期行为

![Uploading Screenshot_20240608_045013_net.kdt.pojavlaunch.zh.jpg…]()

### 其他信息

```markdown
- 设备型号：华为nova3
- CPU 架构：麒麟970
- Android 版本：HarmonyOS 2.0
- PojavZH 版本：1.2.0.1
```

**Comment by HopiHopy** [comment]
@Rogertaf 请提供启动器日志文件，或启动器崩溃报告文件，此截图无法给出更多有效信息

**Comment by Rogertaf** [comment]
> @Rogertaf 请提供启动器日志文件，或启动器崩溃报告文件，此截图无法给出更多有效信息

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch.zh/net.kdt.pojavlaunch.ExitActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d003b
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3554)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3738)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0d003b
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:299)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2390)
	at android.content.res.Resources.getLayout(Resources.java:1341)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:498)
	at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:344)
	at android.app.Dialog.setContentView(Dialog.java:835)
	at com.movtery.ui.dialog.ExitDialog.<init>(ExitDialog.java:28)
	at net.kdt.pojavlaunch.ExitActivity.onCreate(ExitActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:7458)
	at android.app.Activity.performCreate(Activity.java:7448)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3533)
	... 11 more

这个行吗

**Comment by Rogertaf** [comment]
> @Rogertaf 请提供启动器日志文件，或启动器崩溃报告文件，此截图无法给出更多有效信息

我又用天机930试了一下，倒是能进去，但是进入世界的时候，就崩溃了。

**Comment by gumen2258** [comment]
麒麟970也是一样的问题，嘤嘤嘤
